version: '1.0'

services:
  web:
    build: .
    container_name: saas-flask
    ports:
      - "8080:5000"
    environment:
      FLASK_ENV: production
      SECRET_KEY: dev-secret-key
      DATABASE_URL: sqlite:///db.sqlite3
      MINIO_ENDPOINT: http://minio:9000
      MINIO_ACCESS_KEY: minioadmin
      MINIO_SECRET_KEY: minioadmin123
      MINIO_BUCKET: tk-image-storage
    depends_on:
      - minio
    restart: always

  minio:
    image: minio/minio
    container_name: minio
    command: server /data --console-address ":9001"
    ports:
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin123
    volumes:
      - minio_data:/data
    restart: always

volumes:
  minio_data:
